### ISSUE TITLE
client crashes when closing user popup before the 7tv avatar is loaded

### ISSUE THREAD

**Issue by sebm253** [SevenTV/chatterino7#100]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

when opening a user popup while the user has a 7tv avatar, clicking away before the avatar is loaded causes the client to crash. this was already fixed once, but it seems like the issue is back: https://github.com/SevenTV/chatterino7/pull/87

when trying to reproduce the bug, give it a couple of tries.

### Screenshots

![juicer chat in a nutshell](https://i.imgur.com/EBkj3Pl.gif)

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit a643ba73f modified) built on with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
Can replicate

**Comment by TroyKomodo** [comment]
Fixed.
