### ISSUE TITLE
Right Click Menu in Message Box Shows Wrong Menu

### ISSUE THREAD

**Issue by 7JEO** [SevenTV/chatterino7#103]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When i right click on the message box it shows  the same menu that right clicking tabs show.  It used to show copy, paste, cut, etc.

### Screenshots

![image](https://user-images.githubusercontent.com/79304571/176443459-a3f9d5e0-860b-4c52-b82a-18fd6079bb1f.png)
![image](https://user-images.githubusercontent.com/79304571/176443558-451f1e72-ec19-4e82-86b0-4d32d2241d0a.png)

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit a643ba73f modified) built on with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 8 Version 6.2 (Build 22000), kernel: 6.2.9200

**Comment by Felanbird** [comment]
~~Cannot replicate - Windows 10~~

Misread - Can replicate

**Comment by Felanbird** [comment]
upstream issue - chatterino/chatterino2#3844
