### ISSUE TITLE
Some Nametag Paints Increase the Size of Usernames on Mac

### ISSUE THREAD

**Issue by seuss02** [SevenTV/chatterino7#107]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Various nametag paints cause a users name to appear much larger when they chat or are mentioned on the newest Nightly release on MacOS

examples: https://imgur.com/a/pygSPaS

### OS and Chatterino Version

Chatterino Nighty Release, Commit: 703f371, 29/06/202
<img width="394" alt="Screen Shot 2022-06-29 at 10 43 02 PM" src="https://user-images.githubusercontent.com/74581754/176604217-e31a4055-32fc-4b1c-be90-58060d4371af.png">

<img width="389" alt="Screen Shot 2022-06-29 at 10 51 10 PM" src="https://user-images.githubusercontent.com/74581754/176604241-ce0077c5-0c31-4adf-b53f-d73e9051db63.png">

<img width="384" alt="Screen Shot 2022-06-29 at 10 43 40 PM" src="https://user-images.githubusercontent.com/74581754/176604254-5e38de8e-7a3d-4da9-a792-abed31826795.png">

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/176603838-2970e4fe-746a-4999-b711-a90d081efae9.png)
Can you upload your images directly to Github please

**Comment by Excellify** [comment]
This is already fixed by #106

**Comment by Felanbird** [comment]
As Excellify has mentioned, (and I assumed but wanted to see your screenshots to be sure) this issue already has a PR to fix it. 
If you'd like to test the changes to make sure your issue is resolved, the artifact with the required `.dmg` can be found [here](https://github.com/SevenTV/chatterino7/actions/runs/2584421359).

**Comment by seuss02** [comment]
That fixes the issue, thank you.
