### ISSUE TITLE
Thoughts on adding 7tv chatterino to the flathub repository? (linux)

### ISSUE THREAD

**Issue by RomEz10** [SevenTV/chatterino7#108]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [x] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

"Flathub is a centralized repository of Flatpak apps. It provides a single point of entry for distributing apps on the most popular Linux distributions. "
I and possibly many others prefer to download flatpaks from flathub rather than manually installing packages. And I was wondering if you plan or might care to add your project to the repository (I'd like to point out that the original chatterino project is there already). 
Although anyone can submit any app, it is advised to contact the developer first. If you want to learn more about flathub and the process of submitting your app you can read about it [here](https://github.com/flathub/flathub/wiki/App-Submission).
I hope this is the right place to request this and that you'd consider it.

Relevant link: https://flathub.org/home

### OS and Chatterino Version

Irrelevant

**Comment by Felanbird** [comment]
You are in luck, it was added to flathub-beta yesterday.
[2022-06-29 10:03:49 UTC] i published chatterino7 on flathub-beta as a beta version until 7tv support gets upstreamed

`flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo && flatpak install flathub-beta chatterino`
