### ISSUE TITLE
Paints render in system messages

### ISSUE THREAD

**Issue by Mm2PL** [SevenTV/chatterino7#111]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Paints render in system messages like timeouts. I would expect that either both the username color is rendered with the paint or none of them. Timeouts should keep the current behavior. /mods; /vips could have paints. Point redemption messages also don't render color therefore they probably shouldn't have paints.

### Screenshots

![Gayge 🌈](https://user-images.githubusercontent.com/25011746/177058963-49c73b9f-a44f-484f-a933-e6ab7a585699.png)

### OS and Chatterino Version

This is on 80a08f582ccaf7011d208ffc0b8b77a4d2c37585, freshly merged into my branch.

**Comment by jupjohn** [comment]
This also applies to hosting messages.

**Comment by TroyKomodo** [comment]
They render for both on my instance
![image](https://user-images.githubusercontent.com/49777269/178380754-d01cab33-e51e-4e4d-ab33-177f9b449a37.png)
![image](https://user-images.githubusercontent.com/49777269/178380894-83049a8d-26dc-4267-9a66-702f673f25da.png)
but you are correct they didnt use to render.

Not sure which way to lean on this, should colors in timeouts be rendered or not?
Perhaps, this is a pr for upstream?

**Comment by averwhy** [comment]
I like having them, I think it should be a setting/toggle

**Comment by Nerixyz** [comment]
> I like having them, I think it should be a setting/toggle

This should be done in Chatterino first (something like "color usernames in system messages"). Feel free to open a discussion there.
