### ISSUE TITLE
Faild to load version information - Update bug?

### ISSUE THREAD

**Issue by ghost** [SevenTV/chatterino7#113]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Shows update button  
click = "Faild to load version information"

More people have the problem it seams

Cant screenshot the error message, sorry 

### Screenshots

![grafik](https://user-images.githubusercontent.com/107950273/178773816-ce99eccf-9231-4f3c-999a-c06adf7cbcc9.png)

### OS and Chatterino Version

Chatterino 7.3.5 on Windows 11

**Comment by Felanbird** [comment]
This should be resolved, the 7TV devs made an unrelated change that just happened to cause this issue for chatterino7.

**Comment by ghost** [comment]
> This should be resolved, the 7TV devs made an unrelated change that just happened to cause this issue for chatterino7.

it is ;)
