### ISSUE TITLE
Emote not rendering in Chatterino

### ISSUE THREAD

**Issue by ArnexTheGuy** [SevenTV/chatterino7#114]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I added a new emote via next.7tv.app in WEBP format to my channel. Emote is not rendered in the Chatterino, while everything is displayed correctly in Dank Chat and the browser.
The problem is not only in Dankerino, which I use, but also in Chatterino7.

Emote name - PauseHYPER

### Screenshots

![изображение](https://user-images.githubusercontent.com/76107821/179214223-3209730d-5478-4830-a50e-d69598f302b5.png)

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.5 on EndeavourOS, kernel: 5.18.10-arch1-1

**Comment by TranRed** [comment]
It seems to happen only with emotes uploaded by the new website.

The CDN URL for the image changed as far as I can see:
Old: `https://cdn.7tv.app/emote/<emoteID>/3x`
New:` https://cdn.7tv.app/emote/<emoteID>/3x.webp`

Might be related to that.

**Comment by AnatoleAM** [comment]
> It seems to happen only with emotes uploaded by the new website.

This is correct. Unfortunately Chatterino was never updated to handle urls as given by the API. The compatibility layer that rewrites `3x` to `3x.webp` cannot work right now until all emotes are re-processed, therefore new emotes will be broken in Chatterino for a few days.

**Comment by Felanbird** [comment]
It appears this issue or something similar is still relevant? 
![image](https://user-images.githubusercontent.com/41973452/185733361-7014e504-dee2-4759-8281-f575fd09e6ae.png)

https://7tv.app/emotes/6266ded14f54759b7184de2d
note: Likely a processing issue, user notes being able to see the emote over 1 month ago

**Comment by AnatoleAM** [comment]
> Likely a processing issue, user notes being able to see the emote over 1 month ago

It's actually much more likely that it's because the higher scales range from 800KB to 3MB, which Chatterino will not display. The solution for this would be to implement AVIF (AV1 Image File Format) support into Chatterino and use the AVIF varients served in the 7TV CDN.
