### ISSUE TITLE
Specific 7tv emotes not showing 

### ISSUE THREAD

**Issue by LeetHaxor** [SevenTV/chatterino7#119]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Just happened recently on Mizkif's channel, with the "SLORPGLORPIN" emote, but this has happened many times in the past. I have tried "Reconnect" and "Reload channel emotes" and it won't update to show the new emote. It shows perfectly fine in native twitch chat, but I can't get it to show in chatterino7. Usually it will show eventually, but I have no idea what causes it to force update or how long it takes. 

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit 132b406cc, built on ) Win 10

**Comment by Felanbird** [comment]
@LeetHaxor enable the setting `Show unlisted / unapproved emotes (7TV only)`

**Comment by Felanbird** [comment]
@LeetHaxor Please change the title back, your issue might help others in the future.
