### ISSUE TITLE
Can't use chatterino7 while using VPN

### ISSUE THREAD

**Issue by kretz1xD** [SevenTV/chatterino7#129]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I've tried Split tunneling. Enabling it fully. Re-install the hole program, both portable version and stable

### OS and Chatterino Version

v7.3.5

**Comment by Felanbird** [comment]
Try using this [nightly build](https://github.com/Felanbird/chatterino2/releases/tag/nightly-build-with-port-change), I went ahead and changed the port on a build specifically for this sort of situation.

**Comment by kretz1xD** [comment]
> Try using this [nightly build](https://github.com/Felanbird/chatterino2/releases/tag/nightly-build-with-port-change), I went ahead and changed the port on a build specifically for this sort of situation.

still doesn't work for me..

**Comment by Felanbird** [comment]
@kretz1xD Were you able to resolve your issue with that build?

**Comment by kretz1xD** [comment]
it's solved. didn't help with what you suggest me to do, it is about their servers. some of them are shadow banned
