### ISSUE TITLE
bttv emotes not loading

### ISSUE THREAD

**Issue by djoker0702** [SevenTV/chatterino7#13]
I installed the 7tv chatterino fork on Linux Ubuntu 20 but all my bttv emotes are not loading, this error is from the logs:
` Failed to fetch BetterTTV channel emotes. (timed out) 
`
I'm not sure if this is a knows issue

**Comment by zneix** [comment]
This has nothing to do with our Chatterino fork, it must've been a temporary issue with your connection to bttv or bttv was just temporarily down. It should fix itself on its own.
