### ISSUE TITLE
Zero Width Emote broken on Chatterino 

### ISSUE THREAD

**Issue by PsycloneTM** [SevenTV/chatterino7#132]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

- When using the emote [DOOR](https://7tv.app/emotes/6167fb43826ba5e06171d4b2) Aliased to "doorTime" in Lirik's Chat it doesn't work on Chatterino.
- Works find on Lirik's chat on browser and when testing in my chat (even with the same alias)

### Screenshots

Lirik Chat (Chatterino)
![Lirik](https://user-images.githubusercontent.com/27637025/188334809-0336bcca-3a63-48dd-bc3a-e9001e17eabe.png)
Lirik Chat (Browser Chat)
![Screenshot 2022-09-04 164702](https://user-images.githubusercontent.com/27637025/188334835-e4f0913d-30dd-496c-92f6-cbceba70f50d.png)
My Chat (Chatterino) 
![Screenshot 2022-09-04 164831](https://user-images.githubusercontent.com/27637025/188335011-61453955-4564-4394-8b40-61170c15d537.png)

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit 411db820 modified, 2022-09-04) Windows 11

**Comment by Felanbird** [comment]
I assume this is the culprit? As they used to work fine.
![image](https://user-images.githubusercontent.com/41973452/188335553-350d1f78-d071-4f3b-928b-bb96f4e15851.png)

**Comment by CycIoneTM** [comment]
Web Extension issue not a Chatterino issue. Has to do with the sub ending and still being able to use the 0-Width emote.

**Comment by Felanbird** [comment]
I have a vague memory of an in-chat discussion that ended in figuring out this happened because LIRIK's 7TV sub had ran out, and channel zero-width emotes are a paid feature. 

Currently seems fine
![image](https://user-images.githubusercontent.com/41973452/203200429-981866e1-f25c-4a45-9ed9-ce7428f1515b.png)
