### ISSUE TITLE
Are you still adding chatterino7 to flathub?

### ISSUE THREAD

**Issue by douglascdev** [SevenTV/chatterino7#137]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Issue #108 was closed and chatterino7 is still not in flathub, do you still plan on adding it there?

I haven't tried installing the beta linked in #108 and it's not visible by searching in flathub anyway, I had to find it by going over the issues.

I was, however, able to modify the [other client's manifest](https://github.com/flathub/com.chatterino.chatterino/blob/master/com.chatterino.chatterino.yml) to this repo and version and install it as a flatpak, so hopefully, it would not take too much work to publish it, and I'd really appreciate it if you did as It would help install and keep the application updated for many Linux distros.

### OS and Chatterino Version

Chatterino 7.3.5

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/190927320-0c8bc635-0753-488f-b886-9bf4c22efb18.png)

**Comment by douglascdev** [comment]
Yeah sorry for repeating the same question, I've seen the issue and linked it but that was 2 months ago, it got closed and it's not on flathub, are you working on it?

**Comment by Felanbird** [comment]
No, the beta release was published to prevent having to deal with uploading the "same" project twice, only the beta will exist on flathub until 7TV is added to chatterino2.

**Comment by oech3** [comment]
Why do not you use different project name?
This app shows same version at version info.
Would you clarify difference of upstream and fork at source URL?
And putting raw .flatpak image on release page of GitHub (if AppImage will be removed)?
