### ISSUE TITLE
Chaterino no longer displays channels being hosted

### ISSUE THREAD

**Issue by doomercreatine** [SevenTV/chatterino7#140]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Previously, the chat client would display a message when the streamer raids/hosts someone along the lines of "[Streamer] is now hosting [other streamer]"

However, recently this message does not display at all. I do not recall when this issue first arose but I want to say it was within the last 7-10 days.

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit f19d9911c modified) built on with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19043

**Comment by Felanbird** [comment]
Twitch deleted hosting the other day
https://www.dexerto.com/entertainment/twitch-is-removing-the-host-feature-and-streamers-are-furious-1924306/

**Comment by 7JEO** [comment]
well hosting doesn't exist anymore. it was removed October 3rd. https://twitter.com/Dexerto/status/1567220585868005378/photo/1
