### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by TomGameZ** [SevenTV/chatterino7#146]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino keeps constantly crashing.

I have tried a full fresh install.

Im Running on 7.3.5 (7TV Addon)

Tried after Windows update, restart and waited for 1 hour.

Looked through Windows Event viewer without finding anything. 

Also logging in crashes the Client instantly.

so far no issues an the "normal" Chatterino2 build juts on the Chatterino7 Build

(EDIT: switched to Nightly Build results no crashing after 1 1/2 hours and same settings. will leave this open but continue to use nightly build.)

### OS and Chatterino Version

Chatterino 7.3.5 | Windows 10 Home (22H2)

**Comment by TroyKomodo** [comment]
Did the nightly stop crashing?

**Comment by TomGameZ** [comment]
> Did the nightly stop crashing?

The Nightly version never started crashing... so technically.. yes

**Comment by TroyKomodo** [comment]
Is this an issue on the latest release tho?

**Comment by TomGameZ** [comment]
i never switched back to the "normal" version.. and probably will not switch back to cause i started liking the nightly build very much more.. so can't tell

**Comment by TroyKomodo** [comment]
Ok then I'll just close this issue then
