### ISSUE TITLE
Installer fails on Windows XP

### ISSUE THREAD

**Issue by 12932** [SevenTV/chatterino7#152]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't seem to install Chatterino7 on Windows XP Service Pack 3,

When I download the installer, and run it, it comes up with the following error

![image](https://user-images.githubusercontent.com/68835423/201481252-a4f8d762-92aa-44b2-b65e-2ad95fa65a6b.png)

The portable version also has the same error

![image](https://user-images.githubusercontent.com/68835423/201481320-11ded154-10d5-4d49-bdc0-aaebbe9e9d99.png)

### OS and Chatterino Version

Chatterino 7.3.5 on Windows XP Service Pack 3

**Comment by 12932** [comment]
Is it because Chatterino is 64-bit? Are there any plans to support a 32 bit version that works on Windows XP?

I know no-one uses Windows XP anymore, I was just wondering if it would work and it would be kinda cool if it did

**Comment by williambulin** [comment]
> Is it because Chatterino is 64-bit? Are there any plans to support a 32 bit version that works on Windows XP?
> 
> I know no-one uses Windows XP anymore, I was just wondering if it would work and it would be kinda cool if it did

You should try on the 64bit edition of Windows XP, just to be sure.

**Comment by TroyKomodo** [comment]
Uh, I think this is an upstream issue.

**Comment by 12932** [comment]
> Uh, I think this is an upstream issue.

what means that

**Comment by TroyKomodo** [comment]
chatterino7 is a fork of the [chatterino2](https://github.com/Chatterino/chatterino2) project. We add extra features specifically related to the features offered by 7TV. Being unable to install on Windows XP is a very unlikely side effect from our changes. You can try by installing the mainstream chatterino and reporting back here if you were successful in doing that. If you were not then I advise you to open an issue on their repo so they can choose to either address this and implement a Windows XP version or tell you that they wont be supporting Windows XP as it is no longer supported by Microsoft's support (likely what they will say) 

If this does turn out to be a bug related to chatterino in general and not us you can reference this issue in the new issue you make on their repo. https://github.com/SevenTV/chatterino7/issues/152 <- copy this link

If this is a bug we introduced then please reopen this issue with some more information.

\- Troy

**Comment by 12932** [comment]
Oh thank you

- 12932
