### ISSUE TITLE
links on Chatterino for Linux do not open in browser when clicked

### ISSUE THREAD

**Issue by 111100001** [SevenTV/chatterino7#153]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

the links in chats cannot be opened by clicking them. i have to copy them and paste in browser.

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc) on Linux Kubunutu

**Comment by 111100001** [comment]
using AppImage version. Cannot install the .deb version; says unsatisfied dependencies

**Comment by Felanbird** [comment]
Duplicate of Chatterino/chatterino2#3207

Kubuntu throws a fit when you try to open links

**Comment by Felanbird** [comment]
@111100001 
![image](https://user-images.githubusercontent.com/41973452/203633291-b63f2b93-0ccb-444c-9efd-3ca1e5fc0cf6.png)

**Comment by 111100001** [comment]
> @111100001 
> ![image](https://user-images.githubusercontent.com/41973452/203633291-b63f2b93-0ccb-444c-9efd-3ca1e5fc0cf6.png)
> 

Thank you so much. it works! and i used penis as a value

but then i would have to launch chatterino using cli and i don't want to do that.

**Comment by Felanbird** [comment]
> but then i would have to launch chatterino using cli and i don't want to do that.

![image](https://user-images.githubusercontent.com/41973452/203636492-94d88297-f014-4a6a-863a-f35d3b8edf47.png)

**Comment by 111100001** [comment]
found something weird.

when i launch chatterino from cli, it opens links! but when i launch it by clicking on the appimage it doesn't open the links

**Comment by 111100001** [comment]
already did! thank you!

**Comment by Felanbird** [comment]
@zurrty I remember that you were also someone who reported this issue, the above conversation ☝️  can resolve this problem for you, if you're still have said problem.
