### ISSUE TITLE
New version doesn't remember logins. 

### ISSUE THREAD

**Issue by techbot2342** [SevenTV/chatterino7#164]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

New version doesn't remember logins. Thought it was 2sv but it is not. It logs you out every time having you to keep putting in a new token. 

### OS and Chatterino Version

Chatterino Nightly 7.4.0 (commit 8f57d63f modified) built on 2022-12-04 with Qt 5.15.2, Windows SDK, MSVC 193431933 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
Once you login, immediately close Chatterino and tell me if your login was kept.

**Comment by techbot2342** [comment]
> Once you login, immediately close Chatterino and tell me if your login was kept.

It was not. It connects once right after you manually log in the first time. It stays stuck on reconnecting until you reconnect via the 3 dots in the top menu. Closed it and reopened and it's asking me to add my account again. I've replicated this like 8 times. I switched to 7.3.5 and it works fine.

**Comment by Felanbird** [comment]
Is your hard drive/SSD at critical levels of full? I do remember an issue where settings would not save if your disk was completely full.

Otherwise, can you replicate this issue on normal [chatterino2](https://github.com/Chatterino/chatterino2/releases)?

**Comment by techbot2342** [comment]
SSD has plenty of space. 200Gb+
I tested it on chatterino2 (2.4.0) and it works fine. I am only having this issue in the chatterino nightly 7.4.0.

**Comment by techbot2342** [comment]
Managed to get it working. Not sure what I did. It looks like the account was cached in the program file or something. I would remove the account and reappear after a reset. Which was weird. I kept doing it like ten times until I managed to make it stop appearing and finally showed up as anonymous. Logged in again and it worked.
