### ISSUE TITLE
highlight priority

### ISSUE THREAD

**Issue by yeahalexander** [SevenTV/chatterino7#165]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

user highlights has priority over message highlights, making me miss messages from people i have highlighted

### Screenshots

what happens:
https://kappa.lol/PeTFU (message from same user without pinging me https://kappa.lol/OaHfp )

what should happen (and used to happen):
https://kappa.lol/Mb9Uf

### OS and Chatterino Version

Chatterino Nightly 7.4.0 (commit 8f57d63f modified) built on 2022-12-04 with Qt 5.15.2, Windows SDK, MSVC 193431933 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
https://github.com/Chatterino/chatterino2/discussions/3865#discussioncomment-3206576
