### ISSUE TITLE
Dependency is not satisfiable: libssl1.1 

### ISSUE THREAD

**Issue by ghost** [SevenTV/chatterino7#172]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't install Chatterino7 Nightly on Linux Mint running in a virtualized environment, but I don't think that is the problem. 
Package manager tells me: 
> Error: Dependency not satisfiable: libssl1.1 

Checking for the policy tells me this:
`apt-cache policy libssl1.1`

`libssl1.1:
 Installed: (none)
 Candidate: (none)
 Version Table: `

The LTS release from Ubuntu 16.04 which Mint is based on comes with libssl1.0.0. 

### OS and Chatterino Version

Chatterino7 v.7.4.0 on Linux Mint Vera 21.1 Kernel 5.15.0-56-generic

**Comment by GersonMJL** [comment]
Having the same problem, it seems that ```libssl1.1``` is deprecated (https://askubuntu.com/questions/1408000/unable-to-locate-package-libssl1-1)

I tried to install using ```dpkg -i Chatterino-x86_64.deb``` and it returned:
```
dpkg: dependency problems prevent configuration of chatterino:
 chatterino depends on libssl1.1; however:
  Package libssl1.1 is not installed.

dpkg: error processing package chatterino (--install):
 dependency problems - leaving unconfigured
```
The solution seems to be upgrading the dependency to ```libssl3```

### OS and Chatterino Version

Chatterino7 v.7.4.0 on Pop!_OS 22.04 Kernel 6.0.12-76060006-generic

**Comment by ghost** [comment]
If I understand that right upgrading to libssl3 only works when building chatterino7/any app in that case? I never dived into libssl so I have no clue, just read the thread you've linked. Please keep in mind that english isn't my native language so I'm sorry if I am missing something obvious.

**Comment by ghost** [comment]
I researched a little more and turns out since Ubuntu dropped the libssl1.1 package completely there seems to be no way to even work around this and install an old libssl package. Spotify had a similar problem a while ago and they needed to create a deb package towards libssl3.

**Comment by Wissididom** [comment]
It will not even work when libssl is satisfied because it'd be installed in `/home/runner/chatterino2` or along those lines. I'm trying to fix it here: https://github.com/Wissididom/chatterino2/pull/9 for quite some time now. I'm now trying to bundle Qt in the deb and adjust LD_LIBRARY_PATH in the postinst script.

**Comment by Wissididom** [comment]
I was now able to get it to work for me so here is a new PR in the upstream Chatterino for it (just to have it linked here): https://github.com/Chatterino/chatterino2/pull/4357

**Comment by pajlada** [comment]
The .deb packages should be generated with proper dependencies now, and are split up depending on if you're on Ubuntu 20.04 or Ubuntu 22.04, you can try them out at https://github.com/Chatterino/chatterino2/releases/tag/nightly-build before they land in this fork

**Comment by Nerixyz** [comment]
I merged the changes. As this fork doesn't build anything prior to Qt 5.15.2, I removed the runner for 20.04 ⇒ only 5.15.2 on Ubuntu 22.04 will be built.
