### ISSUE TITLE
Complications w/ Updating from v7.3.5 to v7.4.0

### ISSUE THREAD

**Issue by Alicyl** [SevenTV/chatterino7#178]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't seem to update from v7.3.5 to v7.4.0 through the built-in installer. This is the error I receive when I try, and it has been this way since v7.4.0's release. Whenever I manually update Chatterino7, I lose _**all**_ of my configurations.

Strangely enough, this does not happen with Chatterino2 as its built-in installer functions as intended for me (successfully updated from v2.3.5 to v2.4.0 there) and my configurations persisted.

Is there a way to get the built-in installer to work or to manually update while keeping my configurations intact?

### Screenshots

![chatterino_wc0mij8c6i](https://user-images.githubusercontent.com/13776859/212456166-46fd3dee-5536-4d1e-801a-74cb8c3c928f.png)
![explorer_akizOrEea1](https://user-images.githubusercontent.com/13776859/212456170-b2d10ce2-ded7-43d3-8906-996b6b626cff.png)
![Myusa5COFN](https://user-images.githubusercontent.com/13776859/212456172-2541d265-7801-48ed-bee9-7c39df52687e.png)

### OS and Chatterino Version

Chatterino v7.3.5 (commit 132b406cc) on Windows 11

**Comment by Felanbird** [comment]
Open the `modes` file in the folder, in any text editor, and remove `portable` and save

**Comment by Alicyl** [comment]
> Open the `modes` file in the folder, in any text editor, and remove `portable` and save

The error gained an extra line after I removed `portable`, but other than that, the same issue occurred: my configurations got nuked, and built-in installer failed.

![chatterino_qigR2tqhTZ](https://user-images.githubusercontent.com/13776859/212457079-8724487b-2de4-4572-bcb2-f8bdd1b275d3.png)

Strangely enough, my configurations seem to be completely tied to that `portable` tag. I did a little experiment and manually installed the v7.4.0 update again then added `portable` below `nightly` in the modes folder, and lo and behold, I got my configurations back while being on the latest update.

There's still something wrong with the built-in installer and my settings being in disarray like a Jenga puzzle though. I just don't know how to diagnose it myself.

**Comment by Felanbird** [comment]
> Strangely enough, my configurations seem to be completely tied to that portable tag. I did a little experiment and manually installed the v7.4.0 update again then added portable below nightly in the modes folder, and lo and behold, I got my configurations back while being on the latest update.

That was what I meant (I should have been clearer), removing portable fixes the issue with the settings not working on the manual update - the auto updater does not work as the 7TV did the release wrong.

**Comment by Alicyl** [comment]
Ahhh, so will future updates from the built-in installer continue to work as intended v7.4.0 onwards or will I have to remember to do a "zig-zag" by removing `portable`, manually updating, then putting it back?

(Closed it before I could say "thanks"! Thanks for the help. <3)

**Comment by Felanbird** [comment]
> Ahhh, so will future updates from the built-in installer continue to work as intended v7.4.0 onwards or will I have to remember to do a "zig-zag" by removing `portable`, manually updating, then putting it back?

I can't see the future so I'm unsure 😄 but likely the issue should not happen on future versions (🙏)
