### ISSUE TITLE
Global follow emotes don't work

### ISSUE THREAD

**Issue by francorz** [SevenTV/chatterino7#190]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Follow emotes don't show in the emote suggest in other channels, only in the channel of streamer (yes, i'm subscribed) 

Other channels:
![image](https://user-images.githubusercontent.com/83022459/219392392-abf9d29c-cf4b-4acb-8bc0-759c1d43bbc4.png)

The sub channel:
![image](https://user-images.githubusercontent.com/83022459/219392643-7305e0fc-00be-4073-9186-c30130754e29.png)

### OS and Chatterino Version

Chatterino Nightly 7.4.0 (commit 88360f6a modified) built on 2023-02-15 with Qt 5.15.2, Windows SDK, MSVC 193431937, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by Nerixyz** [comment]
Tracked upstream in Chatterino/Chatterino2#4233.

**Comment by Nerixyz** [comment]
Closing this, since it's not an issue with this fork.
