### ISSUE TITLE
Updating from 7.4.1 Nightly breaks settings

### ISSUE THREAD

**Issue by Johnnycyan** [SevenTV/chatterino7#194]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I've been using Chatterino Nightly 7.4.1 commit 65e384a9. I just tried updating to the newest release version and it reset all of my settings and I can't seem to find where the new ones are being stored because changing the files in %appdata%/chatterino2 has no effect on the new version.

### OS and Chatterino Version

Chatterino 7.4.1 on Windows 11 Version 22H2

**Comment by Nerixyz** [comment]
Which version did you download exactly?

I suspect you downloaded the portable version. With this version, the settings are located next to the `chatterino.exe` file (probably in `C:\Program Files\Chatterino`). There, if you want to "disable" the portable mode, delete the `modes` file next to the `chatterino.exe`.

**Comment by Johnnycyan** [comment]
Oh shit yeah I didn't realize it would do that. I figured portable and the github actions zips were built the same my bad
