### ISSUE TITLE
[macOS] bundle identifier is still "com.chatterino", same as the original

### ISSUE THREAD

**Issue by core-code** [SevenTV/chatterino7#197]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

since Chatterino7 is a distinct app to the original, the CFBundleIdentifier in the Info.plist file should probably be changed from "com.chatterino" to something different so that the app can be distinguished from the original

### OS and Chatterino Version

7.4.2

**Comment by core-code** [comment]
same problem in 7.5.0

**Comment by Nerixyz** [comment]
I get the problem, but changing this retroactively would cause users that installed an older version of Chatterino7 to have two versions installed, even though they only want one. Not sure what the best solution is.

**Comment by core-code** [comment]
> I get the problem, but changing this retroactively would cause users that installed an older version of Chatterino7 to have two versions installed, even though they only want one.

well, no, why could a bundle-id change cause this?


the only problem when changing the bundle-id of an app is preference migration. if you are using the native cocoa preferences system (NSDefaults), you'll need to kick off a migration from the previous bundle-id.

**Comment by Nerixyz** [comment]
> > I get the problem, but changing this retroactively would cause users that installed an older version of Chatterino7 to have two versions installed, even though they only want one.
> 
> well, no, why could a bundle-id change cause this?
> 
> 
> the only problem when changing the bundle-id of an app is preference migration. if you are using the native cocoa preferences system (NSDefaults), you'll need to kick off a migration from the previous bundle-id.

Yea I have no clue how this works on macos I'd assume if you change the id, then it's a different app to the OS. So if you try to update/reinstall it would add a new app and not overwrite the old one (hence the need for a migration). If you know how that works, feel free to open a PR.

**Comment by core-code** [comment]
> it would add a new app and not overwrite the old one

whether that happens depends on the name of the app in the filesystem, not the bundle-id.

**Comment by core-code** [comment]
thanks!
