### ISSUE TITLE
Emote modifiers Can't be used or displayed

### ISSUE THREAD

**Issue by BeyondSteaLikez** [SevenTV/chatterino7#200]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

i cannot use emote modifiers like w! monkaS

### Screenshots

![image](https://user-images.githubusercontent.com/21991887/226426955-b3f3859e-5418-480c-abe5-72714142b958.png)
![image](https://user-images.githubusercontent.com/21991887/226427025-cf8cbece-3e33-437e-8b37-39df3d305eb5.png)

### OS and Chatterino Version

7,4,2 version

**Comment by AnatoleAM** [comment]
This is unrelated to this repository (these modifiers are not a 7TV feature)

You could make a feature request to the [upstream](https://github.com/chatterino/chatterino2), however I doubt this will ever be added
