### ISSUE TITLE
Chatter replying to a blocked user

### ISSUE THREAD

**Issue by BrotherJohn1** [SevenTV/chatterino7#203]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a chatter replies to someone you have blocked it will show the message that the blocked person said.

### Screenshots

![ce86ucv](https://user-images.githubusercontent.com/87091553/227836791-9df8d300-00a9-4e22-96b0-4cccc8af1ddd.png)

### OS and Chatterino Version

Chatterino 7.4.2 (commit c140c88b) on Windows 10

**Comment by AnatoleAM** [comment]
This isn't an issue relevant to this repo. Submit this on the [upstream](https://github.com/Chatterino/chatterino2) instead.
