### ISSUE TITLE
Messages not sending after being ban-unbanned in specific channel

### ISSUE THREAD

**Issue by AlphaSalami** [SevenTV/chatterino7#210]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Got banned and unbanned from channel. Can view chat, can chat from browser. Can chat in other channels from chatterino, but not from the one I got ban-unbanned from.
Using the latest version, have uninstalled reinstalled, fully cleared cache. 
Cannot see this issue anywhere else nor have ever heard of this from anyone before.

### OS and Chatterino Version

Chatterino Nightly 7.4.2 (commit e76110ce) built on 2023-03-28 with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Nerixyz** [comment]
I think this might be a twitch issue (you might be shadowbanned). If you know the broadcaster, try asking them to VIP you and check if you can type as a VIP.

_Since this isn't 7TV related, I'll transfer this to the upstream repository._

**Comment by AlphaSalami** [comment]
You are correct, I have been shadowbanned from that specific channel. Thanks for your help :)

**Comment by Felanbird** [comment]
> You are correct, I have been shadowbanned from that specific channel. Thanks for your help :)

If you confirmed the issue by having them VIP you as neri suggested, can you have them time you out for any duration, that's how I've seen it resolved.
