### ISSUE TITLE
Viewer list cannot be loaded

### ISSUE THREAD

**Issue by BeyondSteaLikez** [SevenTV/chatterino7#211]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

i click on the "Two people icon on chatterino to view viewer list"
its loading..........

### Screenshots

![image](https://user-images.githubusercontent.com/21991887/230442493-9ec6c4a7-9c59-4ce4-9cd3-830b74d5a08f.png)

### OS and Chatterino Version

Windows 10 7.4.2 version of chatterino

**Comment by Nerixyz** [comment]
Unfortunately, Twitch has shut down the service that Chatterino used. See https://github.com/Chatterino/chatterino2/issues/4494.
