### ISSUE TITLE
Subscriber badges aren't loading

### ISSUE THREAD

**Issue by Startrek852** [SevenTV/chatterino7#221]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [x] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Every channel I open says "Failed to load channel badges - OAuth token is missing" and doesn't show the subscriber badges

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.22621

**Comment by Nerixyz** [comment]
Did you try and re-add your account? The new login might require new scopes for Twitch.

**Comment by Startrek852** [comment]
> Did you try and re-add your account? The new login might require new scopes for Twitch.

I've never been logged in to Chatterino

**Comment by Nerixyz** [comment]
> I've never been logged in to Chatterino

Then I don't think it's possible to get the Twitch badges anymore, as Twitch restricted the API - see https://github.com/Chatterino/chatterino2/issues/4492.

**Comment by Startrek852** [comment]
> Then I don't think it's possible to get the Twitch badges anymore, as Twitch restricted the API - see [Chatterino#4492](https://github.com/Chatterino/chatterino2/issues/4492).

OK, thanks anyways!
