### ISSUE TITLE
7TV Global Emote when trying to do simple smile

### ISSUE THREAD

**Issue by Crocross** [SevenTV/chatterino7#222]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Normally I use the colon `:` key and then start typing an emote name on Twitch without issue. I also sometimes do the basic default emotes like :) or :(
I noticed recently that when doing :) or :( it pops up showing an emote with a name of (7TV) but I unknowingly hit enter to send the message. From what I see (7TV) is an alias of 7tvM however, I think the behaviour is a bit odd overall.
I don't know entirely the best solution but I feel like there should be an added mechanism where :) and :( don't resolve to an emote? Perhaps the pattern has to match something like `^(:\w)` (starts with colon followed by any word character?

### Screenshots

![image](https://github.com/SevenTV/chatterino7/assets/10664890/212e1975-3df3-4285-8ffb-efe2306ba9fb)

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) on Windows 10 Version 2009

**Comment by Crocross** [comment]
uhh.. looks like it somehow fixed itself? Maybe my client was bugging?
![image](https://github.com/SevenTV/chatterino7/assets/10664890/6793370b-2e0e-4cc7-ae63-31a5afc59331)

**Comment by Felanbird** [comment]
Your global Twitch emotes probably just failed to load, if this ever happens again click the 🙂 and go to the `Global` tab and it will be very likely that no Twitch emotes will be available, which should be resolved by a restart of the application. 
(I assume that's what you did after you opened this issue originally)

**Comment by Nerixyz** [comment]
This isn't an issue with this fork. If this is still an issue, please [open one upstream](https://github.com/Chatterino/chatterino2/issues/new).
