### ISSUE TITLE
Missing native Apple Silicon support

### ISSUE THREAD

**Issue by TheFruxz** [SevenTV/chatterino7#225]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The provided macOS version is missing a native Apple Silicon support, only an Intel version is present.

### OS and Chatterino Version

14.0 Beta (23A5257q)

**Comment by Nerixyz** [comment]
Since I don't have a machine with Apple Silicon myself, I'm relying on GitHub to provide runners. They're currently on the roadmap for Q4 of 2023 (see https://github.com/github/roadmap/issues/528).

**Comment by MechanicKitten** [comment]
Looks like it shipped in October https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by Nerixyz** [comment]
> Looks like it shipped in October [github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/)

I'm pretty sure the larger runners are paid. Though, there's a `macos-13` runner now. Since I have no clue how to build stuff on macOS with CMake for both architectures (either as a universal binary or two separate ones), I'd love to see contributions!

**Comment by Nerixyz** [comment]
@TheFruxz and/or @MechanicKitten could you try the new `-arm64` binary in the nightly release (should be ready in about 20min)?

**Comment by MechanicKitten** [comment]
👍 nice, had a quick play around and it appears to work as expected. If I find any problems I'll raise an issue but looks good atm
