### ISSUE TITLE
How to ignore announcement messages?

### ISSUE THREAD

**Issue by ketersu** [SevenTV/chatterino7#226]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I found "ignores" function is not working to ignore bots announcement messages,
Is there any way to do this?

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Nerixyz** [comment]
This is a bug in upstream Chatterino, I filed https://github.com/Chatterino/chatterino2/issues/4694.

**Comment by Felanbird** [comment]
@ketersu As a workaround to the native ignore feature not working, you can use filters. 
`!(flags.sub_message && author.name == "botName")`
![image](https://github.com/SevenTV/chatterino7/assets/41973452/b4aa077d-4c5f-4abd-aebb-d6bb1e6efd99)

If you would like the `Announcement` message to be removed too, you can change the filter to:
`!(message.content == "Announcement" || flags.sub_message && author.name == "botName")`
but this would also remove the `Announcement` message under normal announcements.
![image](https://github.com/SevenTV/chatterino7/assets/41973452/7411a13c-81bc-4444-9683-79b9e6cf4e79)
