### ISSUE TITLE
Not being able to @mention user from message

### ISSUE THREAD

**Issue by yungsamd17** [SevenTV/chatterino7#229]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When trying to **@mention** user from a message _(either just "yungsamd17" or "@yungsamd17")_ it will not **@mention** that user with right-click.

![7TV_Nightly](https://github.com/SevenTV/chatterino7/assets/64147848/3fe41c64-0493-44cd-b790-e4e294a32a6c)

## It seems to work as normal on:

> _(Chatterino 2.4.4 (commit [29a14627](https://github.com/Chatterino/chatterino2/commit/29a14627)) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad
> Running on Windows 10 Version 2009, kernel: 10.0.22621)_
>
> ![Chatterino_2-4-4](https://github.com/SevenTV/chatterino7/assets/64147848/0fe09f0a-867a-4fb9-b39b-156c2e5bfd9c)

### And

> _(Chatterino Nightly 2.4.4 (commit [5ee9697d](https://github.com/Chatterino/chatterino2/commit/5ee9697d)) built on 2023-08-09 with Qt 6.5.0, MSVC 193532217
> Running on Windows 11 Version 22H2, kernel: 10.0.22621)_ 
>
> ![8WnuXRT](https://github.com/SevenTV/chatterino7/assets/64147848/333f560a-975c-4852-b4c3-17d8e4998396)

### OS and Chatterino Version

Windows 11 22H2 - Chatterino Nightly 7.4.4 (commit 670fba29) built on 2023-08-03 with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by Nerixyz** [comment]
This was fixed in b98be3b0f32749354131a6ed3b34a666317a1653 which wasn't merged at the time. It's now merged.
