### ISSUE TITLE
Personal emotes dont stack if they are zero-width in chatterino

### ISSUE THREAD

**Issue by Maikatura** [SevenTV/chatterino7#231]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When having personal emotes in the chatterino client and using zero-width emotes that is your personal emote they dont stack but when doing it in the native chat they do 

### Screenshots

Native chat 
![https://i.imgur.com/D92igov.png](https://i.imgur.com/D92igov.png)

Chatterino 
![https://i.imgur.com/OU3CWVB.png](https://i.imgur.com/OU3CWVB.png)

### OS and Chatterino Version

Chatterino 7.4.4 on Windows 11

**Comment by Nerixyz** [comment]
This is only an issue if you type a personal emote the first time. #199 resolves that.
