### ISSUE TITLE
[macOS] 7tv emotes are not visible on 7.4.5

### ISSUE THREAD

**Issue by BananaSlayer** [SevenTV/chatterino7#237]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

They were visible on 7.4.4, but are not visible on the stable 7.4.5 or the nightly version. They are visible on 2.4.5.
Comparisons (left: 2.4.5, right: 7.4.5) in screenshots

### Screenshots

<img width="678" alt="Screenshot 2023-09-14 at 15 58 44" src="https://github.com/SevenTV/chatterino7/assets/55053877/7d7408e9-04e3-4504-9043-e63d0660a0a6">

<img width="773" alt="Screenshot 2023-09-14 at 15 59 54" src="https://github.com/SevenTV/chatterino7/assets/55053877/63d3b1ef-92b8-4475-93f1-472ef8175dda">

### OS and Chatterino Version

Chatterino 7.4.5 (commit ec0cddb1) on macOS Ventura 13.0.1

**Comment by Nerixyz** [comment]
Can you try installing [`libavif`](https://formulae.brew.sh/formula/libavif) from brew? The AVIF plugin itself is statically linked, but I'm not sure about the library on macOS.

**Comment by BananaSlayer** [comment]
Already have it installed, tried reinstalling it as well to no avail.

**Comment by Nerixyz** [comment]
I (temporarily) disabled libavif on macOS, since it's a pain to statically link there. I'll probably add it back later through conan.

**Comment by Nerixyz** [comment]
Should be fixed with https://github.com/SevenTV/chatterino7/pull/245. I'll add a Qt 6 build later.

**Comment by Nerixyz** [comment]
The AVIF plugin is now bundled with Chatterino. If this is still an issue, please reopen.
