### ISSUE TITLE
User info card no longer displays followers count

### ISSUE THREAD

**Issue by dcmille** [SevenTV/chatterino7#238]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Opening a User Info Card from a split by clicking on a user name.
Info card shows the Followers: label, but the actual count is missing.
Verified using known streamers with followers.

After checking source code, suspect the issue is caused by recent change to Twitch API.
Get Users Followers is now depreciated (2023-09-06) and replaced by Get Channel Followers.

https://dev.twitch.tv/docs/change-log/
2023‑09‑06
This release includes the following updates, detailed in the [Legacy Follows API and Eventsub Shutdown Timeline post here](https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769):

The Get Users Follows API endpoint has been removed.
[Get Channel Followers](https://dev.twitch.tv/docs/api/reference/#get-channel-followers) now requires the user access token to contain both the moderator:read:followers scope and have either the user ID match the broadcaster_id or the user must be a moderator for the specified broadcaster in order to return data about specific followers. This condition is also required for using the user_id parameter.
V1 of [channel.follow](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelfollow) has been removed.

### Screenshots

![Chatterino7 bug](https://github.com/SevenTV/chatterino7/assets/46731456/5c4a9cbf-dbcf-465b-9c3e-5c54654c67e8)

### OS and Chatterino Version

Chatterino  7.4.5 (commit 715305bb) built with Qt 5.15.2,MSVC 193532217

**Comment by dcmille** [comment]
OS Says Windows 10, but its actually Windows 11.
Noticed the fault yesterday (15/9/23), but was working fine prior to that.
As a mod, I use the follower count to help identify other streamers in the chat, and issue shoutouts etc.
(P.S. While I can read the source code, programming in C++ is not in my skill set - Good luck.)

**Comment by Nerixyz** [comment]
This was fixed in 813d96867b0a467de266bf09dc1fa02a3d4f9098 and is in the nightly build. See https://github.com/Chatterino/chatterino2/issues/4808 and https://github.com/Chatterino/chatterino2/issues/4810.

> OS Says Windows 10, but its actually Windows 11.

We're using [`QSysInfo::prettyProductName`](https://doc.qt.io/qt-6/qsysinfo.html#prettyProductName) which should say 11 (maybe it's a bug there?).

**Comment by dcmille** [comment]
Thanks!  Moved to nightlies for a while.
