### ISSUE TITLE
Snapping chatterino to the edge of the screen extends left, right, and bottom sides of the app off screen

### ISSUE THREAD

**Issue by jeovanny315** [SevenTV/chatterino7#24]
Chatterino 7.3.3 (commit 20a71273e)

When I drag chatterino to the edge of the screen on windows 10 to make it half the screen, the left edge is partly on my other monitor and the bottom is partly off screen.

I hope this video makes sense

https://user-images.githubusercontent.com/79304571/124025166-00bab780-d9a5-11eb-9974-ddd3e9031194.mp4

**Comment by Mippy** [comment]
This occurs on the main Chatterino app as well. Might want to open this issue there instead.

**Comment by StephanBruh** [comment]
This is a upstream issue, nothing to do with the chatterino7 fork

**Comment by zneix** [comment]
Might be related to #2205
