### ISSUE TITLE
2 year+ badges are not visible

### ISSUE THREAD

**Issue by ghost** [SevenTV/chatterino7#244]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If you equip a 7TV badge 2 years or above it will not show up in Chatterino7

### OS and Chatterino Version

Chatterino 7.4.4

**Comment by Nerixyz** [comment]
On which OS are you on?

**Comment by ghost** [comment]
> On which OS are you on?

Windows 11, doesn't show for others on same Chatterino with Windows 10

**Comment by Nerixyz** [comment]
> Chatterino 7.4.4

Just noticed you're on an old version. Both https://github.com/SevenTV/chatterino7/releases/tag/v7.4.6 and https://github.com/SevenTV/chatterino7/releases/tag/v7.4.5 should show the badges.

**Comment by ghost** [comment]
> > Chatterino 7.4.4
> 
> Just noticed you're on an old version. Both https://github.com/SevenTV/chatterino7/releases/tag/v7.4.6 and https://github.com/SevenTV/chatterino7/releases/tag/v7.4.5 should show the badges.

Apologies, never saw a new version was out. Thank you!
