### ISSUE TITLE
Chatterino7 version online lower

### ISSUE THREAD

**Issue by hugevibes** [SevenTV/chatterino7#248]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Ever since the 7.4.5 update, Chatterino7 has been asking me to downgrade the version to 7.4.4, the message says: 

"The version online (7.4.4) seems to be lower than the current (7.4.6).
Either a version was reverted or you are running a newer build.
..."

When I dismiss it, it comes back every time I open up Chatterino7. This does not happen to me on Chatterino2, hence the report here. Also happens on portable version. Obviously I am running a newer (stable) build so I thought the message would resolve itself over time but this does not seem to be occuring.

### OS and Chatterino Version

Chatterino 7.4.6 (commit f2d677b2) Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by AnatoleAM** [comment]
fixed via https://github.com/SevenTV/API/pull/230
