### ISSUE TITLE
image uploader

### ISSUE THREAD

**Issue by ukeesz** [SevenTV/chatterino7#25]
image uploader don't working while link preview is enabled (i think its only with s-ul.eu)

![image](https://user-images.githubusercontent.com/86529374/124273894-e3baeb80-db40-11eb-92a3-ba60d879e5c4.png)

**Screenshots**

Windows Chatterino Nightly 7.3.3

**Comment by zneix** [comment]
First of all, image uploader has nothing to do with our fork of Chatterino so if anything, you should've opened an issue on the upstream repository.
Secondly, this doesn't seem like an issue with image uploader, but your config. Did you follow the [example configuration on Chatterino wiki](https://wiki.chatterino.com/Image%20Uploader/#s-uleu)?

> don't working while link preview is enabled

Could you elaborate on this part? What does link preview has to do with that even?

**Comment by zneix** [comment]
Closing in favour of #2944 I guess
