### ISSUE TITLE
Emojis Wont Load 

### ISSUE THREAD

**Issue by lucas19961** [SevenTV/chatterino7#250]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

In the Emotes Menu The Emojis wont load and i dont see them in the Chat.  I tried all 4 Emoji Styles and reinstalling/ cache clear wont help.

### Screenshots

![image](https://github.com/SevenTV/chatterino7/assets/17136546/92513c78-7711-4aff-a695-525224d5b531)
![image](https://github.com/SevenTV/chatterino7/assets/17136546/1a5f4414-40b7-40d2-8791-24da2f10e0b9)
![image](https://github.com/SevenTV/chatterino7/assets/17136546/cad12ea8-97d9-498c-9ed6-783c5930dd91)

### OS and Chatterino Version

Chatterino Nightly 7.4.6 (commit c7a11ebc) built on 2023-10-16 with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by Nerixyz** [comment]
This is a problem with Chatterino itself, not this fork (I could reproduce it on the nightly builds there). Please open an issue there.
