### ISSUE TITLE
Nightly release cannot be installed on Ubuntu

### ISSUE THREAD

**Issue by crazysmc** [SevenTV/chatterino7#253]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Installation of the Ubuntu DEB file `Chatterino-ubuntu-22.04-x86_64.deb` fails as it depends on `libavif` which does not exist in the default repositories.
There are similarly named packages available:
```
$ apt search libavif
Sorting... Done
Full Text Search... Done
libavif-bin/jammy 0.9.3-3 amd64
  Library for handling .avif files (utilities)

libavif-dev/jammy 0.9.3-3 amd64
  Library for handling .avif files (development files)

libavif-gdk-pixbuf/jammy 0.9.3-3 amd64
  Library for handling .avif files (GDK pixbuf plugin)

libavif13/jammy 0.9.3-3 amd64
  Library for handling .avif files

libavifile-0.7-bin/jammy 1:0.7.48~20090503.ds-21 amd64
  toolkit for libavifile

libavifile-0.7-common/jammy,jammy 1:0.7.48~20090503.ds-21 all
  toolkit for libavifile

libavifile-0.7-dev/jammy 1:0.7.48~20090503.ds-21 amd64
  development header files for libavifile

libavifile-0.7c2/jammy 1:0.7.48~20090503.ds-21 amd64
  shared libraries for AVI read/writing
```
However none of which is just named `libavif`.

### OS and Chatterino Version

Chatterino 7.4.6 nightly-build on Ubuntu 22.04.3 LTS

**Comment by Nerixyz** [comment]
Could you try the nightly release once it's built?

**Comment by crazysmc** [comment]
That was the right fix for me and the installation works again, thank you!
