### ISSUE TITLE
Paints not consistently rendering

### ISSUE THREAD

**Issue by averwhy** [SevenTV/chatterino7#259]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Paints arent consistently rendering. they'll sometimes render when you send a first message in a while, or randomly. If you chat a bit, sometimes it will go away. Will add screenshots as i encounter this bug

### OS and Chatterino Version

Chatterino 7.4.6 (commit f2d677b2) built with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Nerixyz** [comment]
Probably something I messed up. I'll look into it, thanks for reporting!

**Comment by averwhy** [comment]
No problem

Heres after i closed and reopened my laptop (hadnt closed chatterino)
![image](https://github.com/SevenTV/chatterino7/assets/43783082/9c61454a-a7e8-49a1-a87c-b24008840a78)

In my own channel: 
![image](https://github.com/SevenTV/chatterino7/assets/43783082/50339ac1-e9db-4a3c-9574-52280a2e7da9)

**Comment by Nerixyz** [comment]
When a new message is sent in that channel, does the paint apply to the other messages?

**Comment by averwhy** [comment]
Sometimes it will, like it will disappear from a bunch of previous messages

Another thing i noticed is sometimes someone with a paint will send a message, then someone else sends a message and that persons paint will disappear. Another screenshot that's sort of related to that:

![image](https://github.com/SevenTV/chatterino7/assets/43783082/956087e8-4e69-4cea-bf59-c9f76398db70)

**Comment by averwhy** [comment]
I wonder if a fix to this could be adding a 'reload 7tv subscriber data' or something similar to this context menu 
![image](https://github.com/SevenTV/chatterino7/assets/43783082/eace5d27-b910-47fa-b478-edfadfa433f3)

**Comment by Nerixyz** [comment]
So as far as I know, this is an issue with the underlying API as this seems to happen in browser chat too. There's no such thing as a single endpoint to get all cosmetics data for all users (as there are too many users with cosmetics afaik).

**Comment by Johnnycyan** [comment]
I wouldn't mind this too much but sometimes when the paint gets lost the entire username disappears until another message is sent by that person

**Comment by Nerixyz** [comment]
If this is still an issue, please reopen this (with a reproducible example).
