### ISSUE TITLE
Certain 7TV emotes not rendering

### ISSUE THREAD

**Issue by ichigo-gyuunyuu** [SevenTV/chatterino7#27]
### **Describe your issue**
Certain 7TV emotes do not render both in chat and the emote menu. 
Example: 
chatterino.image: Error while reading image "https://cdn.7tv.app/emote/60b23db5f659090a743e147e/1x" : ' "Unsupported image format" ' is the output on the terminal

### Screenshots

Actual Behaviour:
![image](https://user-images.githubusercontent.com/15829692/125190307-0b553680-e25a-11eb-816a-4425dc83764c.png)
Expected Behaviour:
![image](https://user-images.githubusercontent.com/15829692/125190344-3b9cd500-e25a-11eb-94a9-da8681b1e9cb.png)

### **OS and Chatterino Version**

OS: Artix Linux
Chatterino Version: Tried both the chatterino2-7tv-git aur and building from the chatterino7 branch

P.S. The expected behaviour screenshot was obtained by using the appimage from the 7.3.3 release, but I don't use that as audio from pings do not work in the appimage.

**Comment by Melonify** [comment]
Have you tried to install the `qt5imageformats` package or equivalent?
I had a similar issue with emotes like this, which I believe is caused by `libwebp` not being installed, the emotes which do render seem to be old ones which were uploaded prior to 7TV converting all emotes to webp.

**Comment by ichigo-gyuunyuu** [comment]
I had a feeling it was due to some missing library, which probably came bundled with the appimage. 
Downloading the `qt5-imageformats` package from the standard Arch repos seemes to have solved the issue. Thanks!

**Comment by hugeblank** [comment]
I'm having this issue in a Debian based OS, and can't find an apt package named `qt5-imageformats` or `libwebp`. If they do exist what is their equivalent name for dpkg/apt?
