### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by prodbyeagle** [SevenTV/chatterino7#273]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Is there any way that there's like an theme/ new ui so its cleaner? fluent ui kinda

### OS and Chatterino Version

Chatterino 7.4.4H1 (commit 6331c15c modified) built with Qt 5.15.2, Windows SDK, MSVC 193431942 Running on Windows 10 Version 2009, kernel: 10.0.26100

**Comment by Nerixyz** [comment]
There are [themes](https://wiki.chatterino.com/Themes/), but they only allow you to customize colors. I think there has been some discussion outside of GitHub about a new design, but that would require a lot of implementation effort (and someone to make an initial mockup first!). Regarding fluent design, there's https://github.com/Chatterino/chatterino2/discussions/3223. https://github.com/Chatterino/chatterino2/issues/2309 talks about using system themes on Linux, which in turn would allow more custom themes (i.e. Qt plugins) to be used.

This isn't an issue with chatterino7 specifically; please open a discussion on [chatterino2](https://github.com/Chatterino/chatterino2/discussions/new/choose) instead.
