### ISSUE TITLE
Failed to fetch 7TV channel emotes. (Error: 403)

### ISSUE THREAD

**Issue by paultoganel** [SevenTV/chatterino7#282]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

the 7TV emotes don't work

### OS and Chatterino Version

Chatterino 7.5.1 on Windows 11

**Comment by AoXNeR** [comment]
found solution?
