### ISSUE TITLE
Chatterino window state issues on secondary monitor with lower resolution after using Alt+Tab

### ISSUE THREAD

**Issue by TeeJay69** [SevenTV/chatterino7#292]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

#### Description
When Chatterino is open on a **secondary monitor** with a lower resolution (1440p) and maximized, the following issue occurs:

1. Clicking the minimize button works as expected initially.
2. Using the **Windows app switcher (Alt+Tab)**—even without switching apps (just pressing **Alt+Tab** and then **Esc**)—causes the issue to start.
3. After this, reopening Chatterino (via taskbar or Alt+Tab) results in:
   - The window being in a "pseudo-maximized" state: almost fullscreen but slightly smaller, with visible gaps at the top and left edges.
   - The minimize button no longer works until manually clicking the "Restore Down" button (middle button), then maximizing again.

This issue **does not occur** on the primary monitor or when using a single monitor setup.

---

#### Steps to Reproduce
1. Set up a multi-monitor configuration:
   - Primary monitor: [Resolution, e.g., 4K].
   - Secondary monitor: [Resolution, e.g., 1440p].
2. Open Chatterino and drag it to the secondary monitor.
3. Maximize Chatterino on the secondary monitor.
4. Minimize Chatterino using the minimize button.
5. Press **Alt+Tab** to open the Windows app switcher. No need to switch apps; press **Esc** to exit the switcher.
6. Reopen Chatterino:
   - Via the taskbar, or
   - By Alt+Tabbing back to it.

> You can see the issue in the video, please note that after I clicked the minimize button, I opened the windows app switcher without switching, which is not visible in the video but already described above.

---

#### Expected Behavior
Chatterino should reopen in a maximized state, and the minimize button should work as expected.

---

#### Actual Behavior
After interacting with the Windows app switcher:
- Chatterino opens in a "pseudo-maximized" state (slightly smaller than fullscreen).
- The minimize button stops working until manually restoring the window state using the "Restore Down" (middle) button and then re-maximizing.

---

#### Additional Observations
- The issue only occurs on the **secondary monitor** (1440p resolution in my setup).
- The issue **does not occur**:
  - When using a single monitor.
  - On the primary monitor.
- Restarting the PC prevents the issue temporarily, as long as **Alt+Tab** is not used.

---

#### Attachments
1. **Screen recording** showing the issue, including:
   - Interaction with the minimize button.
   - Use of the **Windows app switcher (Alt+Tab)**.
   - Reopening Chatterino via taskbar or switcher.
2. Screenshot of **Display Settings** showing monitor arrangement and resolutions.

---

#### Environment
- **Chatterino Version**: Chatterino7 v2.5.2-beta.1 (HAPPENS WITH THE OFFICIAL CHATTERINO AS WELL. I CHECKED BOTH VERSIONS USING FULL UNINSTALLS!!!!!!!! (v2.5.2-beta.1) 
- **Windows Version**: Windows 11 Pro, 23H2
- **Monitor Setup**:
  - Primary monitor: [3840x2160, 125% scale, 144hz].
  - Secondary monitor: [2560x1440, 100% scale, 144hz].

### Screenshots

https://github.com/user-attachments/assets/36f79de5-8818-453a-8598-de0f161a480c

### OS and Chatterino Version

Chatterino7 v2.5.2-beta.1 Windows 11 Pro, 23H2

**Comment by TeeJay69** [comment]
![image](https://github.com/user-attachments/assets/92ee0421-2df2-4c5e-9ec7-d07e9f2b5bca)
![image](https://github.com/user-attachments/assets/3ff1b988-67f2-468f-9cd4-da7be0b249e8)
![image](https://github.com/user-attachments/assets/6ba3b00e-ff58-48bf-a294-87e211cfb56e)
![image](https://github.com/user-attachments/assets/9208fd22-c560-406e-9a08-46a442d13acd)
![image](https://github.com/user-attachments/assets/96af291f-7338-48d8-b81c-dd99a1610c6f)
![image](https://github.com/user-attachments/assets/5d8bdb91-e3e1-42e7-93e2-eebf01f70441)

**Comment by Nerixyz** [comment]
> HAPPENS WITH THE OFFICIAL CHATTERINO AS WELL. I CHECKED BOTH VERSIONS USING FULL UNINSTALLS!!!!!!!!

Please open this in the official repo. It's not related to this fork.

**Comment by TeeJay69** [comment]
I opened it in both repo's
