### ISSUE TITLE
Loading previous messages not working

### ISSUE THREAD

**Issue by gryyyfin** [SevenTV/chatterino7#30]
Loading previous messages that were sent before Chatterino was open is not functional anymore, stopped working this morning when I started Chatterino. I tried reinstalling, didn't work. This feature was working as intended yesterday.

**Comment by gryyyfin** [comment]
Running latest stable version, 7.3.3

**Comment by talneoran** [comment]
This isn't a problem specific to this fork, but rather a temporary issue with the external service used to load recent messages. It seems to currently be down and loading recent messages will fail on both the fork and upstream (and on any version).

**Comment by AnatoleAM** [comment]
This isn't an issue with Chatterino 7.x.x as it would be occuring on upstream as well. But it is most likely the service used to fetch recent messages is currently offline
