### ISSUE TITLE
BTTV doesn't have priority over 7TV

### ISSUE THREAD

**Issue by brian6932** [SevenTV/chatterino7#32]
**Describe your issue**
On FFZ's 7TV add-on, BTTV has priority, however on the Chatterino version, 7TV added emotes with the same name have priority over BTTV. Messing with priority settings on the 7TV emote didn't fix it either.

**Screenshots**
![image_203](https://user-images.githubusercontent.com/18603393/126862387-663884a7-4e2b-4664-beb9-b9064d1a0772.png)
![image_204](https://user-images.githubusercontent.com/18603393/126862479-8bc1b186-e72f-4f56-87a6-4f6f7a2f4421.png)

**OS and Chatterino Version**
Windows 10, Chatterino 452da6bdd

**Comment by AnatoleAM** [comment]
At the moment emote priority is arbitrary. It primarily depends on which provider loads up first. It's up to the individual channels to ensure there are no conflicts

**Comment by brian6932** [comment]
ohhh, then what is this tab supposed to do? 
![image_207](https://user-images.githubusercontent.com/18603393/126873969-5f2c2856-60f1-47ea-92cc-242252cae3c1.png)

**Comment by AnatoleAM** [comment]
It exists as a backend value but it lacks wider client-side implementation for now

**Comment by brian6932** [comment]
Ah, makes sense, thank you

**Comment by Felanbird** [comment]
Closing this because it's chatterino7 and it makes sense to have 7TV priority on the build that existed specifically to add 7TV. Also BTTV has re-taken priority in the chatterino2 implementation.
