### ISSUE TITLE
sub emotes

### ISSUE THREAD

**Issue by HaveANiceDay2** [SevenTV/chatterino7#33]
half of my sub emotes dont show up or duplicate for some weird reason also the app doesnt have a picture (the chatterino logo)
<img width="477" alt="Screen Shot 2021-07-25 at 5 49 46 PM" src="https://user-images.githubusercontent.com/80364575/126919378-fcea4b5f-7945-4e58-b352-600c354561de.png">

**Comment by zneix** [comment]
This has been fixed long time ago and was the upstream Chatterino issue. Please upgrade to [Chatterino 7.3.4](https://github.com/SevenTV/chatterino7/releases/tag/v7.3.4)
