### ISSUE TITLE
Will you please allow "notify when online" notifications without login, or provide a 2.1.0 installer

### ISSUE THREAD

**Issue by barbedknot** [SevenTV/chatterino7#34]
This post will be a disaster to format, so please bear with me.

Chatterino dropped support for Windows 7 on version 2.1.0 (this being the last version supporting windows 7). Coincidentally, Version 2.2.0 was the last one to allow "notify when online" notifications; version 2.2.1 was the first to require logging in to have "notify when online" notifications (there is other functionality logging in allows, but I am not educated on them). Source:

https://web.archive.org/web/20210421115826/https://chatterino.com/
(this is the last screenshot of the website before they changed the design; on this screenshot you can see the text "Last version supporting Windows 7 (2.1.0 64-Bit)")

https://github.com/Chatterino/chatterino2/issues/1915
> chatterino no longer able to pull stream online status while anonymous #1915

I am not sure if chatterino began supporting Windows 7 again or not, but I was no longer able to find mentions of the last Windows 7 version being 2.1.0 past the above screenshot of their website. I was actually able to install the latest version for Windows normally a few weeks ago, despite my operating system being Windows 7, but I reverted back to 2.1.0 just because the latest chatterino required logging in for "notify when online" notifications, as I've established earlier.

Chatterino has professed their unwillingness to allow "notify when online" notifications without login:

https://github.com/Chatterino/chatterino2/issues/2257#issuecomment-739330763
> No. This idea was already brought up before. Chatterino does not want to start helping ban circumventions.

So therein is my difficult to explain feature request. I will try to summarize what I'm asking for:

- A chatterino7 release that is discrepant from the chatterino2 philosophy of not allowing non-logged in users to receive "notify when online" notifications (among other features)
- A chatterino7 release that supports Windows 7 (my understanding was that 2.1.0 was the last version to support Windows 7, but at some point that appears to've changed, so perhaps this is just a given)

I guess that's it? I still had trouble formatting this, even if I can tersely communicate what I wanted, at the end of it. If nothing else, will you please spoonfeed me a chatterino7 version of the 2.1.0 installer? The 2.1.0 version on your github is just the source code, which gave me grey hairs trying to work out. For the time being I'm still on the plain chatterino 2.1.0, which doesn't have 7tv emotes.

edit: removed citing "protection from global bans" quote as demonstrating that chatterino used to willingly allow "notify when online" notifications without login. I realize now that "global bans" likely meant regions in the world, and was independent of their unwillingness to willingly provide this functionality to chatterino users who don't log in.

**Comment by Mm2PL** [comment]
We (Chatterino devs/contributors) made a decision to move Chatterino to use only Helix (the new Twitch API) instead of Kraken (aka v5). Helix doesn't support anonymous title/live checks anymore (bother Twitch about that, not us). **The feature on your old Chatterino version will stop working soon because Kraken is being [DECOMMISSIONED](https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-shutdown-details-and-timeline/32649).**

We don't support Windows 7 anymore, as doesn't Microsoft. We can't support anything indefinitely. This OS is 12 years old, it's about time. Most users have moved to newer *and supported* OSes.

**Comment by barbedknot** [comment]
Well, I somewhat understand. Is a Windows 7 user still able to have a functioning chatterino above version 2.1.0? If so, functioning to what degree?

Also I feel it is dishonest of you to just refuse to acknowledge the quote I cited demonstrating the outright refusal to allow anonymous "live checks" even if it were possible for the foreseeable future. There is a difference between "we could if we would" and "we refuse to". You making a third choice for yourself of "the choice is out of our hands" is too late considering I cited a quote on chatterino's stance on this already.

**Comment by ALazyMeme** [comment]
Hello barbedknot

Thank you for your concerns, I will assist by addressing them one by one.

> Chatterino dropped support for Windows 7 on version 2.1.0

The dropped support was as a result of Microsoft themselves no longer offering support for Windows 7. To users that are on Windows 7, it is highly suggest you upgrade to Windows 10.

> I was actually able to install the latest version for Windows normally a few weeks ago, despite my operating system being Windows 7

Yes, support has been dropped for Windows 7. You may be able to install it, however we have no plans to provide support for bugs/issues on Windows 7 devices.

> * A chatterino7 release that is discrepant from the chatterino2 philosophy of not allowing non-logged in users to receive "notify when online" notifications (among other features)

As already mentioned, we are trying to move away from Kraken as a result of the API being decommissioned. Helix endpoints have a strict requirement for OAuth when trying to use any endpoint as per the API docs: https://dev.twitch.tv/docs/api/reference. This is inclusive of knowing when a stream is online or not. Hence why you are unable to see if a stream is live (and do/see many other things) if you are not logged in.

> * A chatterino7 release that supports Windows 7 (my understanding was that 2.1.0 was the last version to support Windows 7, but at some point that appears to've changed, so perhaps this is just a given)

As aforementioned, Microsoft has dropped all support for Windows 7. Why would we support Windows 7 if the developer doesn't themselves? It seems absolutely preposterous to me.

> Is a Windows 7 user still able to have a functioning Chatterino above version 2.1.0?

Sure, it may work. We still don't provide support for it.

> Also I feel it is dishonest of you to just refuse to acknowledge the quote I cited demonstrating the outright refusal to allow anonymous "live checks" even if it were possible for the foreseeable future. There is a difference between "we could if we would" and "we refuse to". You making a third choice for yourself of "the choice is out of our hands" is too late considering I cited a quote on chatterino's stance on this already.

Chatterino is a community-made, open source project. Nobody gets paid to work on it. I'll put it quite simply; Kraken is not being added into Chatterino, just so users are able to see when a streamer is live in anonymous mode.

Your whole issue revolves around complaining that there's no Windows 7 or Kraken support. Both of which have had all support dropped by their main developers. So I ask you; why would we add support for said feature, if the devs themselves do not support it?

Kind Regards,
ALazyMeme

**Comment by barbedknot** [comment]
> Also I feel it is dishonest of you to just refuse to acknowledge the quote I cited demonstrating the outright refusal to allow anonymous "live checks" even if it were possible for the foreseeable future. There is a difference between "we could if we would" and "we refuse to". You making a third choice for yourself of "the choice is out of our hands" is too late considering I cited a quote on chatterino's stance on this already.

x2

Kind Regards,
person calling out intellectual dishonesty. smiley face
