### ISSUE TITLE
3rd party global emotes not loading

### ISSUE THREAD

**Issue by theballakoala** [SevenTV/chatterino7#37]
**Describe your issue**

3rd party global emotes have a chance of not loading, with at least one set of globals not loading almost every time I launch Chatterino. This only happens with BTTV/FFZ/7TV, Twitch globals load every time.

**Screenshots**

![image](https://user-images.githubusercontent.com/83271078/128618467-65f1c7b0-520a-474f-b0a5-b1854c0ee0f5.png)

![image](https://user-images.githubusercontent.com/83271078/128618491-4f85058f-1866-46c2-a084-1d18650de39c.png)

**OS and Chatterino Version**

 Windows 10, Chatterino 7.3.4

**Comment by zneix** [comment]
Yes, it is known for global third party emotes to not load in sometimes. This is however an upstream Chatterino issue and nothing introduced to our fork. Sometimes, BTTV/FFZ/7TV APIs fail to respond when we ask them for Global emotes. Thing is, global emotes don't get refreshed when you press F5, which should probably be changed somehow. Feel free to open an issue on the upstream Chatterino for this one.
