### ISSUE TITLE
Chatterino7 shifted to the left when using Chatterino Native Host Chrome extension

### ISSUE THREAD

**Issue by deivshon** [SevenTV/chatterino7#41]
Issue:
When using the Chatterino Native Host Chrome extension, Chatterino7 appears shifted to the left compared to where it should be.

Screenshot:

![2021-09-09 16_52_14-](https://user-images.githubusercontent.com/88600810/132709883-ab1536f2-78e2-441c-941a-874c9af41a5b.png)

OS: Windows 10
Chatterino7 Version: 7.3.4

The issue does not appear to exist in versions before 7.3.4.

**Comment by Felanbird** [comment]
Chatterino/chatterino-browser-ext#65
