### ISSUE TITLE
Username highlight in name color broken

### ISSUE THREAD

**Issue by NotNotQuinn** [SevenTV/chatterino7#5]
**Describe your issue**

The name colors on one of the most recent nightly builds  (commit 9b3fe6604) no longer show up.

Type the name of a user who has sent a message in the channel, and their name is typically highlighted in their name color (with my settings).

**Screenshots**

Before (commit 6732b25f3)
![example on 2.3.2](https://i.imgur.com/YuZZOdw.png )

After (commit 9b3fe6604)
![example]( https://i.imgur.com/ZLVlIG3.png )

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 7.3.2 (commit 9b3fe6604)

**Comment by NotNotQuinn** [comment]
Disclaimer: I dont know if this is something that changed when 7tv added something, or if it was from upstream.

**Comment by zneix** [comment]
This is an upstream issue, it's being tracked in #2822
