### ISSUE TITLE
Windows 11 multitasking snapping overlaps other monitor and task bar

### ISSUE THREAD

**Issue by VirtualBytes** [SevenTV/chatterino7#55]
**Describe your issue**
I'm using Windows 11 and when using chatterino and snapping it to the right side of the screen a bit of chatterino overlaps under and on the other monitor

**Screenshots**
Display before snapping (showing no overlap to other monitor):
https://i.imgur.com/NK6gyqI.png

After snapping (Red lines display where chatterino overlaps):
https://i.imgur.com/5cIvcZj.png

**OS and Chatterino Version**
Windows 11, Chatterino 7.3.4

**Comment by Felanbird** [comment]
Same as https://github.com/Chatterino/chatterino2/issues/3202 but as stated in that issue, see https://github.com/Chatterino/chatterino2/issues/2205
