### ISSUE TITLE
overwatch league emotes not showing up in emote tab and cant tab it 

### ISSUE THREAD

**Issue by hamnomc** [SevenTV/chatterino7#56]
so yea its exclusively the overwatch league emotes i can still see pride emotes or other empotes that you could get in twitch like 2fa and such in the emotes tab under global but the overwatch league is missing and another anyoing thing is that the glitchcon emotes are still in the subs tab if that could be moved to the global tab it would be cool 

im on windows 10 on chatarino 7.3.4

**Comment by Felanbird** [comment]
https://github.com/Chatterino/chatterino2/issues/3154#issuecomment-895529300

`tl;dr:` We are aware of the issue but have no way of fixing it, and as of right now we have no indication Twitch will offer us a new way of obtaining these emotes via the Helix API, meaning we'll have no way of continuing support for the ones that currently work after the v5 api shutdown in Feb 2022.
