### ISSUE TITLE
Not showing channel point rewards

### ISSUE THREAD

**Issue by TheRealDadbeard** [SevenTV/chatterino7#61]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I suddenly have no messages that show which channel reward has been redeemed. I tried reconnecting and even using latest nightly but nothing worked. They are just not showing.

### OS and Chatterino Version

Nightly 7.3.4 Windows 11

**Comment by zneix** [comment]
Duyplicate of #3163, tl;dr it's random and you just might need to restart your Chatterino sometimes.
