### ISSUE TITLE
Failed to fetch 7TV channel emotes (unknown error)

### ISSUE THREAD

**Issue by TheRealDadbeard** [SevenTV/chatterino7#65]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I just get this error. Nothing else. No logs nothing.

### Screenshots

![grafik](https://user-images.githubusercontent.com/23340600/148438267-d1542685-3ec4-41f2-b0e6-dc321896edf7.png)

### OS and Chatterino Version

Nightly 7.3.4 Windows 11

**Comment by Felanbird** [comment]
Could be a few reasons, see #58 
Try loading the API directly in browser. https://api.7tv.app/v2/users/therealdadbeard/emotes

**Comment by TheRealDadbeard** [comment]
It just started to work again.

**Comment by Felanbird** [comment]
I'll go ahead and close this then, it was very likely your connection to 7tv was blocked by something, if it happens again try that link I posted above and see if the link loads, but this is very unlikely a Chatterino issue.
