### ISSUE TITLE
Red arrow

### ISSUE THREAD

**Issue by dlajsoueioa** [SevenTV/chatterino7#7]
**Describe your issue**

 Red update arrow at the top of Chatterino.

**Screenshots**

![update arrow](https://user-images.githubusercontent.com/84947041/119917290-41ea2280-bf34-11eb-83a0-b68dcf6bdf7c.png)
![when you click on it](https://user-images.githubusercontent.com/84947041/119917291-41ea2280-bf34-11eb-8d67-64da58df96f6.png)

**OS and Chatterino Version**
Windows 10, Chatterino 7.3.2

**Comment by AnatoleAM** [comment]
The fork switches the update server URL, we're just waiting on information for making auto-updates work. Until then i'll show that red arrow since the server is returning uncomplete data.

**Comment by zneix** [comment]
This is worth fixing anyway

**Comment by zneix** [comment]
This has been fixed in https://github.com/SevenTV/ServerGo/commit/58d4c5b74467f43a6c37d6bfb753556ee601e823
