### ISSUE TITLE
"Open stream in browser" not functional on Linux

### ISSUE THREAD

**Issue by zurrty** [SevenTV/chatterino7#70]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I cannot use the "Open stream in browser" function on Chatterino 7.3.4. However, when I tried this on Chatterino 2.3.4 it worked fine. I'm using Firefox as my main browser if that makes any difference.

### OS and Chatterino Version

Chatterino 7.3.4 (commit 2d3fe1fe) on Kubuntu 21.10

**Comment by Felanbird** [comment]
Anything in terminal? Wouldn't be the first time Kubuntu was being a pain.

**Comment by zurrty** [comment]
I tried running it in terminal and now when I try to open a stream in the browser it outputs `Segmentation fault (core dumped)`.

**Comment by tintinmaster** [comment]
Cannot reproduce on Linux Mint 20.3

**Comment by zneix** [comment]
issue on upstream, xdg-open is broken on your distro.
