### ISSUE TITLE
Tooltips for zero-width emotes are inaccessable

### ISSUE THREAD

**Issue by jammehcow** [SevenTV/chatterino7#72]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a zero-width emote is posted along side a standard emote, only a tooltip for the standard emote is shown no matter where the mouse is hovered.

### Screenshots

N/A

### OS and Chatterino Version

Chatterino 7.3.4 (commit 530dcc3c)

**Comment by jammehcow** [comment]
I have a few thoughts on how to better handle this:
 - Show 2 tooltips when hovering over an emote that borders with a zero-width (might require a rework of tooltips, I think there's only ever one available)
 - Show both emotes in the tooltip, stacked on top of each other
 - Use some wizardry to get the topmost opaque emote under the mouse and only show that one. Could cause problems with semi-transparent emotes that cover 100% of the area

**Comment by Mm2PL** [comment]
Feels like an upstream issue

**Comment by Felanbird** [comment]
> Feels like an upstream issue

Makes sense, I was thinking it was something more than just the normal issue where u can "fix" it by clicking above the normal emote, but I see that can be done with the 7tv zero-width as well.

**Comment by jammehcow** [comment]
Pushed up.
