### ISSUE TITLE
[Mac OS] Twitch emotes not available

### ISSUE THREAD

**Issue by meetch09** [SevenTV/chatterino7#76]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

[Mac OS] In the last day or two, Twitch emotes have become unavailable. This includes both sub emotes and Twitch global emotes. 7TV, BTTV, and FFZ emotes are still working. I have signed out & in through the Chatterino app, re-installed, and signed out & in through Twitch external permissions. I have used Chatterino for months and never before had this issue. Using Chatterino 7.3.4 but also tried on 2.3.4 and had the same issue.

### OS and Chatterino Version

Chatterino 7.3.4 (commit 2d3fe1fe) on macOS Big Sur 11.6.5

**Comment by Felanbird** [comment]
Twitch emotes come from Twitch - this is very likely an issue between `You<->Twitch`

That being said, `2.3.5-beta` released a few hours ago so try updating your `2.3.4` and see if that fixes it, although it's unlikely.
⚙️ -> search "beta" and toggle on `receive beta updates` -> click the ⬆️ inbetween your username and ⚙️

**Comment by meetch09** [comment]
I tried the beta and even some older builds but still nothing. Can't seem to figure out what's causing the issue but no Twitch emotes are showing. I can link my Twitch account fine and I even can see the Chatterino permission granted. Maybe it is a macOS issue? Probably grasping at straws, going on day 3 or 4 of the issue.

**Comment by AnatoleAM** [comment]
If you downloaded the nightly build it may have been at the time when it was reverted to vanilla Chatterino due to an accidental push on the master branch, if so download again.

**Comment by Felanbird** [comment]
> Twitch emotes come from Twitch - this is very likely an issue between `You<->Twitch`

A lot of people in certain communities are on macOS and I've sadly heard no other complaints.

**Comment by Felanbird** [comment]
> If you downloaded the nightly build it may have been at the time when it was reverted to vanilla Chatterino due to an accidental push on the master branch, if so download again.

While this was true, it's probably unlikely as I specified trying the beta build of `2.3.5` as there was no `7.3.5-beta` at the time of my comment.

**Comment by Felanbird** [comment]
@meetch09 You wouldn't happen to be VPN'd would you?

**Comment by meetch09** [comment]
I am not VPN'd, and have tried both nightly build and 2.3.5 beta. Do you know any way I could have messed up something on Twitch's side? Everything seems to be in order, and to my knowledge, I did not change anything. The issue arose before the 2.3.5 beta was released.

**Comment by Felanbird** [comment]
> I am not VPN'd, and have tried both nightly build and 2.3.5 beta. Do you know any way I could have messed up something on Twitch's side? Everything seems to be in order, and to my knowledge, I did not change anything. The issue arose before the 2.3.5 beta was released.

Not of the top of my head, are you able to resolve this URL in browser? https://static-cdn.jtvnw.net/emoticons/v2/80481/default/dark/3.0

**Comment by meetch09** [comment]
> > I am not VPN'd, and have tried both nightly build and 2.3.5 beta. Do you know any way I could have messed up something on Twitch's side? Everything seems to be in order, and to my knowledge, I did not change anything. The issue arose before the 2.3.5 beta was released.
> 
> Not of the top of my head, are you able to resolve this URL in browser? https://static-cdn.jtvnw.net/emoticons/v2/80481/default/dark/3.0

yes, resolved fine

**Comment by Felanbird** [comment]
@meetch09 I should ask just incase, you are able to see Twitch badges correct?

If yes, are you able to compare connecting to Twitch with a mobile phone application such as [Chatsen](https://apps.apple.com/us/app/chatsen/id1574037007)[iOS] or [Dankchat](https://play.google.com/store/apps/details?id=com.flxrs.dankchat)[android] 
![image](https://user-images.githubusercontent.com/41973452/160557174-bc2b1ba1-f03d-45b4-a753-9a1a799186e3.png)
![image](https://user-images.githubusercontent.com/41973452/160557193-49f52196-8e2e-40f2-a420-8bedb34ec060.png)
we're basically just brainstorming anything.



[Chatsen/github](https://github.com/chatsen/chatsen)
[Dankchat/github](https://github.com/flex3r/DankChat)

**Comment by meetch09** [comment]
yes, I have chatsen on my phone and it works fine on the same account. I can also see Twitch badges fine on Chatterino. I can see 3rd party channel emotes on Chatterino as well. 
<img width="296" alt="Screenshot at Mar 29 03-39-18" src="https://user-images.githubusercontent.com/102490426/160559205-5718187b-bd76-4223-aa1a-053b17f07741.png">
<img width="298" alt="Screenshot at Mar 29 03-38-56" src="https://user-images.githubusercontent.com/102490426/160559206-e34d5fc6-1878-49c2-b1cf-36b52dad0c5f.png">

**Comment by meetch09** [comment]
I should also add that the twitch emotes show up in chat when I manually type them, I just can't get them to show up when I click the button to show all emotes or through the : auto-fill

**Comment by jammehcow** [comment]
![image](https://user-images.githubusercontent.com/4962764/160560944-e17420bd-387c-47cc-89d8-f4f49cbe917c.png)
Have been able to reproduce on a macOS VM. Very odd, will see what I can find.

**Comment by jammehcow** [comment]
Ignore above, can't see global emotes anymore when you're not logged in. After logging in I can see global emotes so :man_shrugging:

**Comment by meetch09** [comment]
Dang. Well, I appreciate your looking into it. I've logged in and out a few times now, so I'm definitely logged in and can chat through my account, yet the issue persists. Maybe it will resolve itself 🤷‍♂️ I can update tomorrow if nothing changes. Thanks again.

**Comment by meetch09** [comment]
The issue seems to have resolved itself. Not too sure what it was, but I appreciate who helped.
