### ISSUE TITLE
'Tab' button doesnt auto finish emotes

### ISSUE THREAD

**Issue by TaeBNY** [SevenTV/chatterino7#80]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

- When i type the middle of a emote for example
- The Twitch Emote BatChest
- If i type "Chest 'Tab' " it used to finish the emote and replace "Chest" With "BatChest"
- I downloaded the most recent update today and i dont know if i just dont have the right setting checked or if this is just a issue. I have the same settings as the old version i had aswell. 

### OS and Chatterino Version

Chatterino 2.3.5

**Comment by TroyKomodo** [comment]
Uh, can you confirm this is the case with the upstream chatterino?
https://chatterino.com

**Comment by TaeBNY** [comment]
Im just using the chatterino from the 7TV website dont know what upstream
is.

**Comment by TroyKomodo** [comment]
This issue is related to chatterino in general not us. And also is already reported on upstream
https://github.com/Chatterino/Chatterino2/issues/3440
There is also a fix there.

**Comment by Felanbird** [comment]
That issue is for the same setting influencing commands, but emotes work as intended in this issue on both upstream and chatterino7 with `Only search for emote autocompletion at the start of emote names` disabled.

So disable that setting as maybe it's value was reset.
