### ISSUE TITLE
deb package is still 7.3.4-259-g132b406c

### ISSUE THREAD

**Issue by rapidreporter** [SevenTV/chatterino7#81]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The deb package on chatterino 7.3.5 is still 7.3.4-259-g132b406c.
Means not really an issue. 
Just to let you know. ;)

### OS and Chatterino Version

7.3.4-259-g132b406c

**Comment by TroyKomodo** [comment]
It seems that ci builds a different version of the deb file. i will investigate for you.

**Comment by TroyKomodo** [comment]
It seems that the version is a mistake, it is the correct version but the number didnt get updated.
