### ISSUE TITLE
New 7TV emotes not automatically available 

### ISSUE THREAD

**Issue by Nerxxy** [SevenTV/chatterino7#83]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When adding 7TV emotes they don't automatically become usable like they do in normal twitch chat.

Can only use the new emote once chatterino has been restarted.

Not sure if this is a bug, limitation or just something not worked on yet, but would be nice to have :)

### Screenshots

https://user-images.githubusercontent.com/37718547/162588582-843ec5c1-5b29-41ab-a2bb-ff8df992f1ae.mp4

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc) Windows 10 21H2

**Comment by AnatoleAM** [comment]
Turn on the setting.

![image](https://user-images.githubusercontent.com/9599344/162588821-dea087ae-716b-4037-a371-ad2bf8b91241.png)

**Comment by AnatoleAM** [comment]
Oh, thought you meant newly created emotes. What you're referring to is the event API, which is just not implemented in Chatterino. Someone began an implementation that you can track at #75. In the meantime use F5 to refresh
