### ISSUE TITLE
Some emotes are different speed in Chatterino and on 7TV

### ISSUE THREAD

**Issue by VulpesHD** [SevenTV/chatterino7#85]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Example emote:
https://7tv.app/emotes/625637c15c62fecb05d639b9
Fast on 7TV, slow in Chatterino.

### Screenshots

in chatterino: https://i.imgur.com/VnM0OYi.gif

### OS and Chatterino Version

Chatterino 7.3.5 Windows 10 64bit

**Comment by TroyKomodo** [comment]
Interesting, what was the original emote you uploaded?

**Comment by leon-richardt** [comment]
We've been adjusting playback speeds since https://github.com/Chatterino/chatterino2/pull/3506, could be related to this issue in some way.

**Comment by TroyKomodo** [comment]
@VulpesHD is this still the case?

**Comment by VulpesHD** [comment]
> @VulpesHD is this still the case?

Yes, I'm on the most recent build.
