### ISSUE TITLE
sourpls is just an empty void on the mac chatterino

### ISSUE THREAD

**Issue by HaveANiceDay2** [SevenTV/chatterino7#88]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

it simply doesnt show up at all but I can hover over it and it says its sourpls but there's nothing there

### Screenshots

<img width="430" alt="Screen Shot 2022-05-15 at 11 20 01 AM" src="https://user-images.githubusercontent.com/80364575/168487919-2de48292-f4cf-494c-993c-aa2de328aa93.png">
<img width="519" alt="Screen Shot 2022-05-15 at 11 21 28 AM" src="https://user-images.githubusercontent.com/80364575/168487982-a449765d-9de8-478d-8485-8fb8b00bec1a.png">

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc) on macOS

**Comment by TroyKomodo** [comment]
@HaveANiceDay2 is this the bttv emote? or is this a 7tv emote?
Also, does this problem happen on the upstream https://chatterino.com version?

**Comment by HaveANiceDay2** [comment]
it’s the global bttv emote, it doesn’t even show up on the emote menu but
shows up on the colon search. someone said to clear my cache and that
didn’t do anything

**Comment by Felanbird** [comment]
> someone said to clear my cache and that didn’t do anything

that's unlucky b/c that was my only idea
![image](https://user-images.githubusercontent.com/41973452/169180158-1a0effab-85da-4072-bc30-df6c12113245.png)

**Comment by TroyKomodo** [comment]
Please can u install the normal chatterino and check if the problem persists

**Comment by HaveANiceDay2** [comment]
yea this issue is just smth with my computer imma just clear anything
chatterino related on my computer and see
[image: Screen Shot 2022-05-18 at 6.15.48 PM.png]

**Comment by HaveANiceDay2** [comment]
ok got it to work thanks for the help

**Comment by TroyKomodo** [comment]
@HaveANiceDay2 can u tell us what u did to fix it?

**Comment by HaveANiceDay2** [comment]
i just opened app directory and deleted all the folders there lmao

**Comment by TroyKomodo** [comment]
ok cool thanks, ill close this issue
